### ISSUE TITLE
Missing Dependency Notification on Vcode

### ISSUE THREAD

**Issue by Allenjdm** [nasa/vscode-pvs#7]
I recently downloaded VCode and was asked to dowload a PVS then after  choosing a location on my laptop for the PVS a notive pops up saying that my laptop is missing dependency. That vscode is typically ran on lynux and mac not on windows (which is my operating system). I checked to make sure I was running the latest version of vcode and Im pretty sure that I am, I even dowloaded the windows version, so I am unsure what exactly I am to do at this point. I have recently enrolled at Lambda and one of the platforms I have been asked to download and register with is vcode. The notice also said that if I continue to get the alert even after double checking the version I downloaded to report it to githib. So here I am.

**Comment by pmasci** [comment]
Thanks for reporting the problem.
VSCode-PVS runs only under Linux and MacOS for now -- the reason is that PVS is only available for those two platforms.
To use VSCode-PVS under Windows, you will need to create a virtual machine with Linux, and install VSCode and VSCode-PVS in the virtual machine.
I hope this clarifies.
-- Paolo
